### ISSUE TITLE
move to cwl GitHub organization

### ISSUE THREAD

**Issue by mr-c** [giannisdoukas/ipython2cwl#24]
@giannisdoukas If you add me as an owner here I can do the move

**Comment by giannisdoukas** [comment]
Sure! I will add you

**Comment by giannisdoukas** [comment]
It think you have permission now to move it, don't you? @mr-c

**Comment by mr-c** [comment]
> It think you have permission now to move it, don't you? @mr-c

I can't see the settings. Am I listed as an "owner"?

**Comment by giannisdoukas** [comment]
Can you please have a look once again? I didn’t manage to find a way to add you as an owner so I sent you a request to transfer it to you

**Comment by mr-c** [comment]
Done, thanks!
